# Generated by Django 3.1.4 on 2020-12-17 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retrospection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
