# Generated by Django 2.1.1 on 2021-01-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospection', '0004_auto_20201227_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='thought',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
